version: "3.8"

services:
  backend:
    build:
      context: ../aspnet-core
      dockerfile: .docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - "ASPNETCORE_URLS=http://+:5000"
    networks:
      - app-network

  frontend:
    depends_on:
      - backend
    build:
      context: ../angular
      dockerfile: .docker/Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
